trigger:
- master

jobs:
- job: BuildTest
  displayName: 'Ubuntu 18.04'
  pool: 'Ubuntu1804'
  steps:
  - bash: |
      pip3 install --user meson ninja
    displayName: 'Preparing Meson and Ninja'

  - bash: |
      meson build 
    displayName: 'Meson build'

  - bash: |
      ninja -C build 
    displayName: 'Building'

  - bash: |
      ninja -C build test
    displayName: 'Testing'
    continueOnError: true
