trigger:
- master

jobs:
- job: BuildTest
  displayName: 'Ubuntu 18.04'
  pool: 'Ubuntu1804'
  steps:
  - bash: |
      pip3 install --user meson ninja
    displayName: 'Preparing Meson and Ninja'

  - bash: |
      meson build 
    displayName: 'Meson build'

  - bash: |
      ninja -C build 
    displayName: 'Building'

  - bash: |
      ninja -C build test
    displayName: 'Testing'
    continueOnError: true

- job: BuildPackageUbuntu1604
  dependsOn: BuildTest
  displayName: "Packaging for Ubuntu 16.04"
  pool: 'HwangsaeulUbuntu1604'
  steps:
  - template: ci/debianize-steps.yml

- job: BuildPackageUbuntu1804
  dependsOn: BuildTest
  displayName: "Packaging for Ubuntu 18.04"
  pool: 'HwangsaeulUbuntu1804'
  steps:
  - template: ci/debianize-steps.yml

