trigger:
- master

jobs:
- job: BuildTest
  displayName: 'Build Test'
  pool: 'Ubuntu1804'
  steps:
  - bash: |
      pip3 install --user meson ninja
    displayName: 'Preparing Meson'

  - bash: |
      meson build 
    displayName: 'Meson build'

  - bash: |
      ninja -C build 
    displayName: 'Ninja build'

- job: DebianizeUbuntu1604
  displayName: 'Build deb for ubuntu 16.04'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      sudo apt-get update && \
      sudo apt-get install --assume-yes software-properties-common && \
      sudo add-apt-repository ppa:hwangsaeul/ppa && \
      sudo apt-get update && \
      sudo apt-get install --assume-yes -t xenial-backports debhelper meson && \
      sudo apt-get install --assume-yes \
        libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
        libsrt-dev gstreamer1.0-plugins-good git

    displayName: 'Install build packages'

  - bash: |
      dpkg-buildpackage -us -uc
    displayName: 'Build debian packages'
