name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.1
        with:
          action: build
          directory: build
          options: --verbose
          meson-version: 0.54
          ninja-version: 1.9.0
