name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
      - name: Install meson dependencies
        run: |
          python -m pip install scikit-build   

      - name: Add H8L ppa
        run: |
          sudo apt-get install --assume-yes software-properties-common
          sudo add-apt-repository ppa:hwangsaeul/nightly
          sudo apt-get update

      - name: Install package dependencies
        run: |
          sudo apt-get install --assume-yes \
                  libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
                  gstreamer1.0-plugins-good \
                  gstreamer1.0-plugins-bad \
                  gstreamer1.0-plugins-ugly \
                  libsrt-dev \
                  libjson-glib-dev \
                  meson ninja-build 
      - name: Meson Build
        run: |
          meson build
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Build
          path: build/meson-logs/meson-log.txt
      - name: Meson Test
        run: |
          meson test -C build -v --setup debug
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Test
          path: build/meson-logs/testlog-debug.txt
