name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
      - name: Install meson dependencies
        run: |
          python -m pip install scikit-build   

      - name: Add H8L ppa
        run: |
          sudo apt-get install --assume-yes software-properties-common
          sudo add-apt-repository ppa:hwangsaeul/stable
          sudo apt-get update

      - name: Install package dependencies
        run: |
          sudo apt-get install --assume-yes \
                  libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev \
                  gstreamer1.0-plugins-good \
                  gstreamer1.0-plugins-bad \
                  gstreamer1.0-plugins-ugly \
                  libsrt-dev \
                  libjson-glib-dev

      - uses: BSFishy/meson-build@v1.0.1
        with:
          action: build
          directory: build
          options: --verbose
          meson-version: 0.54
          ninja-version: 1.9.0
